server:
  port: 8082

spring:
  datasource:
    name: mybatisplusdb
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://49.233.105.21:3306/mybatisplusdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.kgc.yxlx.pojo
